# Generated by Django 2.2.3 on 2020-05-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltaIncidencia',
            fields=[
                ('numero_alta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('iderror', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_error', models.CharField(max_length=25)),
                ('clase_error', models.CharField(max_length=8)),
                ('prioridad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
                ('tipo_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SolucionIncidencia',
            fields=[
                ('numero_solucion', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField()),
                ('fecha_fin', models.DateField()),
                ('tecnico', models.CharField(max_length=5)),
                ('numero_alta', models.ForeignKey(db_column='numero_alta', on_delete=django.db.models.deletion.DO_NOTHING, to='Principal.AltaIncidencia')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('serial_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='Principal.Departamentos')),
            ],
        ),
        migrations.AddField(
            model_name='altaincidencia',
            name='codigo',
            field=models.ForeignKey(db_column='codigo', on_delete=django.db.models.deletion.DO_NOTHING, to='Principal.Usuarios'),
        ),
        migrations.AddField(
            model_name='altaincidencia',
            name='iderror',
            field=models.ForeignKey(db_column='iderror', on_delete=django.db.models.deletion.DO_NOTHING, to='Principal.Errores'),
        ),
        migrations.AddField(
            model_name='altaincidencia',
            name='serial_number',
            field=models.ForeignKey(db_column='serial_number', on_delete=django.db.models.deletion.DO_NOTHING, to='Principal.Dispositivos'),
        ),
    ]
